
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

struct military {
    string name;
    uint attackPower;
    uint protectionPower;
    int numberLives;
    address addrMillitary;
    string status;
}

interface InterfaceGameObject {
    function acceptAttack(uint attPower) external;
}

interface InterfaceBaseStation {

    function addMilitaryToBaseStation(military unit) external;
    function removeMilitary(address addrMillitary) external;
}
