
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "Military.sol";

// This is class that describes you smart contract.
contract Warrior is Military {

    uint AttackPower = 4;   // cила атаки
    uint ProtectionPower = 3;   // cила защиты
    int NumberLives = 5;   // количество жизни

    constructor() public {
        // check that contract's public key is set
        require(tvm.pubkey() != 0, 101);
        // Check that message has signature (msg.pubkey() is not zero) and message is signed with the owner's private key
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
    }

    // Создание война
    function createWarrior() public checkOwnerAndAccept {
        tvm.accept();
        getAttackPower(AttackPower);   // Получить силу атаки
        getProtectionPower(ProtectionPower);   // получить силу защиты
        unit = military ("Warrior", myAttackPower, myProtectionPower, NumberLives, address(this), "Alive");
    }

    // Характеристики война
    function _characteristicsWarrior() public view returns(military){
        tvm.accept();
        return unit;
    }
}
